# Generated by Django 5.0.2 on 2024-10-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile_pic.png', upload_to='profile_pics/'),
        ),
    ]
