# Generated by Django 5.0.2 on 2024-10-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
